import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

live_config_reload = true

[window]
padding = { x = 1, y = 1 }

[font]
normal = { family = "Monaspace Neon", style = "Regular" }
size = 10
