#!/usr/bin/env bash

export BAR_COLOR=0xFF1B222D

export ITEM_COLOR=0xFF39465E
export ITEM_SECONDARY_COLOR=0xFF98A7C5
export ITEM_HIGHLIGHT=0xFFFFFFFF

export ICON_COLOR=0xFFFFFFFF
export ICON_HIGHLIGHT="$ITEM_COLOR"

export LABEL_COLOR=0xFF9CA2AE
export LABEL_HIGHLIGHT="$ITEM_COLOR"

export SPACE_NATIVE_FULLSCREEN=0xFFFFD484

export BORDER=0xFFBFC0C3
