#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

export BAR_BG=0xFF1B222D

export SPACE=0xFF39465E
export SPACE_SELECTED=0xFFFFFFFF
export SPACE_ICON=0xFFFFFFFF
export SPACE_ICON_HIGHLIGHT=$SPACE
export SPACE_APP=0xFF9CA2AE
export SPACE_APP_HIGHLIGHT=$SPACE
export SPACE_NATIVE_FULLSCREEN=0xFFFFD484
export SPACE_BORDER=0xFFBFC0C3

export LAYOUT_BACKGROUND=0xFF98A7C5
