#!/usr/bin/env bash

# import colors
source "$CONFIG_DIR/colors.sh"

# setting global variables
ITEMS_DIR="$CONFIG_DIR/items"

FONT_FAMILY="JetBrains Mono"
FONT_WEIGHT="Regular"
FONT_SIZE="12.0"

export FONT="${FONT_FAMILY}:${FONT_WEIGHT}:${FONT_SIZE}"

BAR_PADDING=3
ITEM_PADDING=5
INTERNAL_PADDING=8

bar=(
    color="$BAR_COLOR"

    position=bottom
    height=34
    margin=0

    padding_left="$BAR_PADDING"
    padding_right="$BAR_PADDING"

    topmost=window
    sticky=off
    shadow=off
)

sketchybar --bar "${bar[@]}"

# default options
defaults=(
    # geometry
    padding_left="$ITEM_PADDING"
    padding_right="$ITEM_PADDING"

    # background
    background.color="$ITEM_COLOR"
    background.border_color="0x00FFFFFF"

    background.border_width=2

    background.height=28
    background.corner_radius=5

    # icon
    icon.padding_left="$INTERNAL_PADDING"
    icon.padding_right="$INTERNAL_PADDING"

    icon.color="$ICON_COLOR"
    icon.highlight_color="$ICON_HIGHLIGHT"
    icon.font="$FONT"

    # label
    label.padding_left="$INTERNAL_PADDING"
    label.padding_right="$INTERNAL_PADDING"

    label.color="$LABEL_COLOR"
    label.highlight_color="$LABEL_HIGHLIGHT"
    label.font="$FONT"
)

sketchybar --default "${defaults[@]}"

# add left side items
source "$ITEMS_DIR/spaces.sh"
source "$ITEMS_DIR/layout.sh"
source "$ITEMS_DIR/apps.sh"

# final steps
sketchybar --hotload on
sketchybar --update
