#!/bin/bash

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEMS_DIR="$CONFIG_DIR/items"

FONT="FiraCode Nerd Font"
APP_FONT="app-font"
BAR_PADDING=3
PADDING=5

# Bar Appearance
bar=(
    position=bottom
    height=34
    color=$BAR_BG
    shadow=off
    sticky=off
    padding_left=$BAR_PADDING
    padding_right=$BAR_PADDING
    margin=0
    topmost=window
)

sketchybar --bar "${bar[@]}"

# Changing Defaults
defaults=(
    icon.font="$ICON_FONT:Bold:14.0"
    icon.color=$BASE8
    icon.padding_left=$PADDING
    icon.padding_right=$PADDING

    label.font="$FONT:Regular:13.0"
    label.color=$BASE8
    label.padding_left=$PADDING
    label.padding_right=$PADDING

    padding_left=$PADDING
    padding_right=$PADDING

    background.height=28
    background.corner_radius=5
    background.border_width=2

    popup.background.corner_radius=20
    popup.background.border_width=2
    popup.background.border_color=$BASE8
    popup.background.color=$POPUP_BG
    popup.background.shadow.drawing=on
    popup.blur_radius=20
)

sketchybar --default "${defaults[@]}"

# Adding Left Items
# source "$ITEMS_DIR/apple.sh"
source "$ITEMS_DIR/spaces.sh"
source "$ITEMS_DIR/layout.sh"
source "$ITEMS_DIR/apps.sh"
# source "$ITEMS_DIR/front_app.sh"

# Adding Right Items
# source "$ITEMS_DIR/clock.sh"
# source "$ITEMS_DIR/volume.sh"
# source "$ITEMS_DIR/wifi.sh"
# source "$ITEMS_DIR/battery.sh"
# source "$ITEMS_DIR/keyboard.sh"

# right icon padding adjustments
# source "$PLUGIN_DIR/padding_adjustment.sh"

# Finishing
sketchybar --hotload on
sketchybar --update
yabai -m config external_bar all:0:34
