#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global config
PADDING=8

# check if sketchybar is running
if [ -z "$(pgrep -i sketchybar)" ]; then
    EXTERNAL_BAR=0
else
    EXTERNAL_BAR=34
fi

yabai -m config                                         \
    external_bar                all:0:$EXTERNAL_BAR     \
    mouse_follows_focus         off                     \
    focus_follows_mouse         autofocus               \
    window_placement            second_child            \
    window_zoom_persist         on                      \
    window_shadow               on                      \
    window_opacity              on                      \
    window_opacity_duration     0.0                     \
    active_window_opacity       1.0                     \
    normal_window_opacity       1.0                     \
    window_animation_duration   0.00                    \
    insert_feedback_color       0xff000000              \
    split_ratio                 0.5                     \
    split_type                  auto                    \
    auto_balance                off                     \
    mouse_modifier              fn                      \
    mouse_action1               move                    \
    mouse_action2               resize                  \
    mouse_drop_action           swap                    \
                                                        \
    layout                      stack                   \
    top_padding                 $PADDING                \
    bottom_padding              $PADDING                \
    left_padding                $PADDING                \
    right_padding               $PADDING                \
    window_gap                  $PADDING

# space 1: general
yabai -m rule --add app="Thunderbird" space=1
yabai -m rule --add app="Messages"    space=1
yabai -m rule --add app="Calendar"    space=1

# space 2: development
yabai -m rule --add app="Visual Studio Code"  space=2
yabai -m rule --add app="Emacs"               space=2
yabai -m rule --add app="Alacritty"           space=2
yabai -m rule --add app="kitty"               space=2
yabai -m space 2 --layout bsp

# space 3: web
yabai -m rule --add app="Vivaldi"   space=3

# float apps
yabai -m rule --add app="^(System Settings|\
                           Finder|\
                           Digital Color Meter|\
                           Shottr|\
                           1Password|\
                           Font Book|\
                           ProtonVPN|\
                           OneDrive|\
                           Shottr|\
                           Nextcloud|\
                           Google Drive|\
                           Box|\
                           Creative Cloud|\
                           Homerow|\
                           Archive Utility|\
                           Calculator|\
                           Bartender 5)$"\
                    manage=off
yabai -m rule --add label="About This Mac" app="System Information" manage=off
yabai -m rule --add title="Developer Tools" manage=off

# events
yabai -m signal --add event=space_created action="sketchybar --trigger space_created"
yabai -m signal --add event=space_destroyed action="sketchybar --trigger space_destroyed"
yabai -m signal --add event=window_title_changed action="sketchybar --trigger front_app_switched"

echo "yabai configuration loaded.."
